version: '3.9'

services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:4000
    networks:
      - app-network
 
  mongo:
    image: mongo:latest
    container_name: mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: