version: '3.9'

services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    # depends_on:
    #   - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"

  mongo:
    image: mongo:latest
    container_name: mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
