name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx to enable multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. Build the Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -f client/Dockerfile -t my-frontend:latest ./client

      # 5. Build the Backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -f server/Dockerfile -t my-backend:latest ./server

      # 6. Push Docker images to Docker Hub or GitHub Container Registry
      - name: Push Docker images
        run: |
          echo "${{ secrets.Jry_Uh.7FWf4TSt }}" | docker login -u "${{ secrets.ruperix16 }}" --password-stdin
          docker tag my-frontend:latest ruperix16/my-frontend:latest
          docker tag my-backend:latest ruperix16/my-backend:latest
          docker push ruperix16/my-frontend:latest
          docker push ruperix16/my-backend:latest

      # 7. Deploy the containers using Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
